// Idée #49 — "Cadrage qui apprend de toi": a new project INHERITS the
// recurring preferences detected across past projects (tone/ambiance,
// typography, layout, palette trends, UX habits) to shorten the founding
// cadrage. This is the core "cerveau personnel" signal: cross-project,
// workspace-level, generated by synthesis, zero-weight when empty.
//
// Modelled on design-system.ts (same load/save/promptSection shape) and
// lexique.ts (same injectable deps pattern, errors swallowed, no throw).
// Stored at workspace/.preferences.md alongside .design-system.md.
import path from "node:path";
import fs from "node:fs";
import { askLLM } from "./llm-engine.js";
import { loadDesignSystem } from "./design-system.js";
import { loadLanguage, loadThinkingStyle } from "./identity.js";
import { listProjects, projectDir } from "./projects.js";
import { loadMiroir } from "./miroir.js";

export const PREFERENCES_FILE_NAME = ".preferences.md";
const PREFERENCES_MAX_CHARS = 2500;
// Cap on how many projects we aggregate (keep the synthesis prompt bounded).
const MAX_PROJECTS = 12;

function loadCapped(file: string, maxChars: number): string {
  try {
    const text = fs.readFileSync(file, "utf8").trim();
    return text.length > maxChars
      ? `${text.slice(0, maxChars)}\n[... tronqué à ${maxChars} caractères — condense le fichier]`
      : text;
  } catch {
    return "";
  }
}

export function loadPreferences(workspaceDir: string): string {
  return loadCapped(path.join(workspaceDir, PREFERENCES_FILE_NAME), PREFERENCES_MAX_CHARS);
}

export function savePreferences(workspaceDir: string, content: string): void {
  fs.mkdirSync(workspaceDir, { recursive: true });
  fs.writeFileSync(path.join(workspaceDir, PREFERENCES_FILE_NAME), content, "utf8");
}

/** System-prompt section injecting learned preferences ("" if empty — zero
 *  weight before any projects exist). When present, carries BOTH the
 *  inheritance instruction AND the content so the agent knows to surface
 *  them as soft defaults, never force them. */
export function preferencesPromptSection(workspaceDir: string): string {
  const content = loadPreferences(workspaceDir);
  if (!content) return "";
  return `\n\nPréférences récurrentes apprises sur tes projets passés (#49) — inherit these as STATED, OVERRIDABLE defaults when cadrage-ing a NEW project, to shorten the cadrage; surface them ("d'habitude tu pars sur…") and never force them over an explicit user choice:\n${content}`;
}

// Injectable brains so learnPreferences is testable without the network.
// Defaults wire the real ($0 subscription) engine; tests pass mocks.
export interface PreferencesDeps {
  ask: (system: string, user: string) => Promise<string>;
}

const defaultDeps: PreferencesDeps = {
  ask: (system, user) => askLLM(system, user, { maxTokens: 1200 }),
};

/**
 * Aggregates cross-project signals and (re-)generates .preferences.md via
 * askLLM. Signals: design-system, identity layers (language + thinking),
 * and each project's .miroir.md (validated palette/ambiance/structure).
 * If ALL signals are empty → no-op (no ask, no file written).
 * Errors are swallowed — this function never throws.
 */
export async function learnPreferences(
  workspaceDir: string,
  deps: PreferencesDeps = defaultDeps,
): Promise<void> {
  try {
    // Collect workspace-level signals
    const designSystem = loadDesignSystem(workspaceDir);
    const language = loadLanguage(workspaceDir);
    const thinkingStyle = loadThinkingStyle(workspaceDir);

    // Collect per-project signals (miroirs of validated projects, capped)
    const projects = listProjects().slice(0, MAX_PROJECTS);
    const miroirSignals: string[] = [];
    for (const name of projects) {
      const miroir = loadMiroir(projectDir(name));
      if (miroir) miroirSignals.push(`### Projet: ${name}\n${miroir}`);
    }

    // Guard: if every signal is empty → nothing to learn yet
    const hasSignals =
      designSystem || language || thinkingStyle || miroirSignals.length > 0;
    if (!hasSignals) return;

    const signalBlock = [
      designSystem ? `## Design system cross-projet\n${designSystem}` : "",
      language ? `## Vocabulaire personnel\n${language}` : "",
      thinkingStyle ? `## Style de pensée\n${thinkingStyle}` : "",
      miroirSignals.length > 0
        ? `## Miroirs de projets validés\n${miroirSignals.join("\n\n")}`
        : "",
    ]
      .filter(Boolean)
      .join("\n\n");

    const system =
      "Tu es un analyste de préférences design/UX. Tu lis des signaux cross-projets (design system, identité, miroirs validés) et tu en extrais UNIQUEMENT les tendances RÉCURRENTES — celles qui reviennent sur PLUSIEURS projets. Tu produis un markdown court, ancré sur les signaux réels, jamais inventé.";

    const user = `Voici les signaux cross-projets de cet utilisateur :\n\n${signalBlock}\n\nSynthétise UNIQUEMENT les préférences RÉCURRENTES (ton/ambiance, typographie, layout, tendances de palette, habitudes UX). Conditions strictes :\n- N'invente rien qui ne soit pas ancré dans les signaux ci-dessus.\n- Ne mentionne une tendance que si elle apparaît sur PLUSIEURS projets ou est explicitement notée comme récurrente.\n- Sortie = markdown titré "# Préférences apprises", 5 à 10 puces max, concis.\n- Si les signaux ne révèlent aucune tendance récurrente, écris uniquement "# Préférences apprises\n(aucune tendance récurrente détectée pour l'instant)" et rien d'autre.`;

    let draft = "";
    try {
      draft = await deps.ask(system, user);
    } catch {
      return; // errors swallowed — never disrupt the caller
    }
    draft = draft.trim();
    if (!draft) return;
    savePreferences(workspaceDir, draft);
  } catch {
    return; // outer guard — never throw
  }
}
